import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

interface OvertimeData {
  id: string;
  date: string;
  start_time: string;
  end_time: string;
  reason: string;
  department_name: string;
}

interface EmployeeData {
  full_name: string;
  payroll_number: string;
  position_name: string;
}

export const generateSPKLPDF = async (overtime: OvertimeData, employee: EmployeeData): Promise<Blob> => {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  // Colors
  const primaryColor = [31, 41, 55]; // Gray 800
  const accentColor = [37, 99, 235]; // Blue 600

  // Header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
  doc.text("LABERSA", 20, 20);
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text("Group of Hotels & Resorts", 20, 25);

  doc.setDrawColor(200);
  doc.line(20, 30, 190, 30);

  // Title
  doc.setFontSize(16);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text("SURAT PERINTAH KERJA LEMBUR (SPKL)", 105, 45, { align: "center" });
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Nomor: SPKL/${overtime.id.substring(0, 8).toUpperCase()}/${new Date().getFullYear()}`, 105, 52, { align: "center" });

  // Employee Info Section
  doc.setFont("helvetica", "bold");
  doc.text("DIBERIKAN KEPADA:", 20, 65);
  
  const employeeInfo = [
    ["Nama Karyawan", `: ${employee.full_name}`],
    ["Nomor Payroll", `: ${employee.payroll_number}`],
    ["Jabatan", `: ${employee.position_name}`],
    ["Departemen", `: ${overtime.department_name}`],
  ];

  autoTable(doc, {
    startY: 70,
    margin: { left: 20 },
    body: employeeInfo,
    theme: "plain",
    styles: { fontSize: 10, cellPadding: 1 },
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 40 } },
  });

  // Overtime Details Section
  const currentY = (doc as any).lastAutoTable.finalY + 10;
  doc.setFont("helvetica", "bold");
  doc.text("DETAIL PEKERJAAN LEMBUR:", 20, currentY);

  const detailInfo = [
    ["Hari / Tanggal", `: ${new Date(overtime.date).toLocaleDateString("id-ID", { weekday: 'long', day: '2-digit', month: 'long', year: 'numeric' })}`],
    ["Waktu", `: ${overtime.start_time} s/d ${overtime.end_time}`],
    ["Alasan / Tujuan", `: ${overtime.reason}`],
  ];

  autoTable(doc, {
    startY: currentY + 5,
    margin: { left: 20 },
    body: detailInfo,
    theme: "plain",
    styles: { fontSize: 10, cellPadding: 1 },
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 40 } },
  });

  // Terms Section
  const termsY = (doc as any).lastAutoTable.finalY + 15;
  doc.setFontSize(9);
  doc.setFont("helvetica", "italic");
  doc.text("Catatan:", 20, termsY);
  doc.text("1. Karyawan wajib melakukan absen lembur pada saat memulai dan selesai bekerja.", 25, termsY + 5);
  doc.text("2. SPKL ini merupakan bukti sah untuk perhitungan upah lembur.", 25, termsY + 10);

  // Signatures
  const signY = termsY + 30;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  
  doc.text("Disetujui oleh,", 25, signY);
  doc.text("Diterima oleh,", 140, signY);

  doc.setFont("helvetica", "bold");
  doc.text("( ____________________ )", 25, signY + 30);
  doc.text("( ____________________ )", 140, signY + 30);
  
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text("Manager Departemen", 38, signY + 35);
  doc.text("Karyawan", 158, signY + 35);

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(`Dicetak pada: ${new Date().toLocaleString("id-ID")}`, 20, 285);
  doc.text("Generated by HRIS System", 190, 285, { align: "right" });

  return doc.output("blob");
};
